name: shape_cam
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_config: ^1.0.8
  get: ^3.26.0
  http: ^0.12.2
  image_picker: ^0.6.2+3
  google_fonts: ^1.1.2
  rating_bar: ^0.2.0
  font_awesome_flutter: ^8.12.0
  shared_preferences: ^0.5.12+4



flutter:

  uses-material-design: true

  assets:
    - images/

